' ============================================================================
'  SPRITES.bas -- optional PIXEL-ART layer.
'
'  Loads transparent PNG sprites from assets/pixel-art/ (generated by ~/pixelmon)
'  on demand, caches them, and blits them scaled-to-fit into a box. Everything is
'  gated by opt_artstyle (0 = ANSI only), and every path is graceful when the file
'  isn't there yet -- so the game runs identically whether or not the art exists.
'  The pixel art COMPLEMENTS the ANSI board; it never replaces it.
' ============================================================================

' Cached image handle for a pixel-art file, loaded once. 0 = missing / failed
' (the miss is cached too, so a missing file isn't re-probed every frame).
FUNCTION Sprite& (path AS STRING)
    DIM i AS INTEGER, h AS LONG
    FOR i = 1 TO SPR_N
        IF SPR_PATH(i) = path THEN Sprite& = SPR_H(i): EXIT FUNCTION
    NEXT
    IF SPR_N >= UBOUND(SPR_H) THEN Sprite& = 0: EXIT FUNCTION
    h = 0
    IF _FILEEXISTS(path) THEN
        h = _LOADIMAGE(path, 32)                  ' 32-bit keeps the alpha channel
        IF h = -1 THEN h = 0                       ' -1 = load failed
    END IF
    SPR_N = SPR_N + 1: SPR_PATH(SPR_N) = path: SPR_H(SPR_N) = h
    Sprite& = h
END FUNCTION

' Blit a sprite scaled to fit inside a px box, centred, aspect preserved.
' Returns TRUE if something was drawn (i.e. the sprite exists).
FUNCTION DrawSpriteFit% (path AS STRING, bx AS INTEGER, by AS INTEGER, bw AS INTEGER, bh AS INTEGER)
    DIM h AS LONG, iw AS INTEGER, ih AS INTEGER, sc AS SINGLE, dw AS INTEGER, dh AS INTEGER, dx AS INTEGER, dy AS INTEGER
    DrawSpriteFit% = 0
    h = Sprite&(path)
    IF h = 0 THEN EXIT FUNCTION
    iw = _WIDTH(h): ih = _HEIGHT(h)
    IF iw < 1 OR ih < 1 THEN EXIT FUNCTION
    sc = bw / iw
    IF bh / ih < sc THEN sc = bh / ih
    dw = INT(iw * sc): dh = INT(ih * sc)
    IF dw < 1 THEN dw = 1
    IF dh < 1 THEN dh = 1
    dx = bx + (bw - dw) \ 2: dy = by + (bh - dh) \ 2
    _PUTIMAGE (dx, dy)-(dx + dw, dy + dh), h, CANVAS
    DrawSpriteFit% = -1
END FUNCTION

' Normalise a name to a sprite base: lower-case, spaces/slashes -> hyphens, drop a
' trailing plural 's'. "GIANT RATS" -> "giant-rat", "BLACK PUDDING" -> "black-pudding".
FUNCTION SpriteBase$ (nm AS STRING)
    DIM s AS STRING, o AS STRING, i AS INTEGER, c AS STRING
    s = LCASE$(_TRIM$(nm))
    o = ""
    FOR i = 1 TO LEN(s)
        c = MID$(s, i, 1)
        IF c = " " OR c = "/" OR c = "'" THEN c = "-"
        o = o + c
    NEXT
    IF RIGHT$(o, 1) = "s" AND LEN(o) > 3 THEN o = LEFT$(o, LEN(o) - 1)
    SpriteBase$ = o
END FUNCTION

' Path to a monster's sprite (searches the six category folders). "" if none.
FUNCTION MonsterSprite$ (nm AS STRING)
    DIM sbase AS STRING, i AS INTEGER, p AS STRING
    DIM cats(1 TO 6) AS STRING
    cats(1) = "humanoids": cats(2) = "animals": cats(3) = "insects"
    cats(4) = "misc": cats(5) = "beasts": cats(6) = "undead"
    sbase = SpriteBase$(nm)
    MonsterSprite$ = ""
    FOR i = 1 TO 6
        p = "assets/pixel-art/monsters/" + cats(i) + "/" + sbase + ".png"
        IF _FILEEXISTS(p) THEN MonsterSprite$ = p: EXIT FUNCTION
    NEXT
END FUNCTION

' Path to a class portrait (1 Hero / 2 Elf / 3 Superhero / 4 Wizard). "" if none.
FUNCTION ClassSprite$ (pc AS INTEGER)
    DIM nm AS STRING
    SELECT CASE pc
        CASE 1: nm = "hero"
        CASE 2: nm = "elf"
        CASE 3: nm = "superhero"
        CASE 4: nm = "wizard"
        CASE ELSE: nm = ""
    END SELECT
    IF nm = "" THEN ClassSprite$ = "" ELSE ClassSprite$ = "assets/pixel-art/classes/" + nm + ".png"
END FUNCTION

' The short room name for a level -- the part after "LEVEL n - " (e.g.
' "KING'S QUARTERS"), so a location caption fits its box. Falls back to whole label.
FUNCTION RoomShortName$ (sec AS INTEGER)
    DIM s AS STRING, p AS INTEGER
    IF sec < 1 OR sec > 9 THEN RoomShortName$ = "": EXIT FUNCTION
    s = _TRIM$(SECTORS(sec).label)
    p = INSTR(s, " - ")
    IF p > 0 THEN s = _TRIM$(MID$(s, p + 3))
    RoomShortName$ = s
END FUNCTION

' Path to a level's location/scene sprite (assets/pixel-art/rooms). The nine
' sectors don't name their sprites 1:1, so map each to its closest scene. "" if none.
FUNCTION LocationSprite$ (sec AS INTEGER)
    DIM nm AS STRING, p AS STRING
    SELECT CASE sec
        CASE 1: nm = "main-gallery"                 ' MAIN GALLERY
        CASE 2: nm = "barracks"                     ' GUARD ROOM
        CASE 3: nm = "armory"                       ' ARMORY
        CASE 4: nm = "stone-room"                   ' STORE ROOM
        CASE 5: nm = "torture-chamber"              ' TORTURE CHAMBER
        CASE 6: nm = "kings-treasure"               ' KING'S QUARTERS
        CASE 7: nm = "wizards-lab"                  ' WIZ'S QUARTERS
        CASE 8: nm = "queens-treasure"              ' QUEEN'S QUARTERS
        CASE 9: nm = "the-crypt"                    ' THE CRYPT
        CASE ELSE: nm = ""
    END SELECT
    IF nm = "" THEN LocationSprite$ = "": EXIT FUNCTION
    p = "assets/pixel-art/rooms/" + nm + ".png"
    IF _FILEEXISTS(p) THEN LocationSprite$ = p ELSE LocationSprite$ = ""
END FUNCTION

' Draw one framed art box with a caption bar, anchored to a character-cell rect.
' Cols/rows are cells; the art is fit inside and the caption centred in a bar just
' above the frame. Drawn on CANVAS (persists behind the GL dice / banners).
SUB CombatArtBox (path AS STRING, col AS INTEGER, cols AS INTEGER, row AS INTEGER, rows AS INTEGER, caption AS STRING, edge AS _UNSIGNED LONG)
    DIM bx AS INTEGER, by AS INTEGER, bw AS INTEGER, bh AS INTEGER
    DIM capx AS INTEGER, capy AS INTEGER, cap AS STRING
    bx = col * CW: by = row * CH: bw = cols * CW: bh = rows * CH
    _DEST CANVAS
    ' caption bar: one text row above the frame, same width
    capy = by - 4 - CH
    LINE (bx - 4, capy - 2)-(bx + bw + 4, by - 4), BOXBG, BF
    LINE (bx - 4, capy - 2)-(bx + bw + 4, by - 4), edge, B
    ' the framed art box
    LINE (bx - 4, by - 4)-(bx + bw + 4, by + bh + 4), BOXBG, BF
    LINE (bx - 4, by - 4)-(bx + bw + 4, by + bh + 4), edge, B
    IF DrawSpriteFit%(path, bx, by, bw, bh) THEN
        cap = caption
        IF LEN(cap) > cols + 2 THEN cap = LEFT$(cap, cols + 2)   ' never spill the bar
        capx = bx + (bw - LEN(cap) * CW) \ 2
        IF capx < bx - 4 THEN capx = bx - 4
        COLOR edge, BOXBG: _PRINTSTRING (capx, capy), cap
    END IF
END SUB

' Draw the combat art -- the monster portrait framed top-LEFT and the location
' scene framed top-RIGHT -- on CANVAS. Positioned clear of the centre dice tray
' (rows ~9-22), the banner (rows 21-30), the D&D combat panel (rows 39-49) and the
' HUD (row 50), so it stays painted through a whole fight in BOTH combat modes.
' Pixel-art modes only; each half is skipped silently if its sprite is absent.
SUB DrawCombatArt (nm AS STRING, sec AS INTEGER)
    DIM mp AS STRING, lp AS STRING
    IF opt_artstyle = 0 THEN EXIT SUB
    mp = MonsterSprite$(nm)
    lp = LocationSprite$(sec)
    IF LEN(mp) > 0 THEN CombatArtBox mp, 1, 18, 4, 12, "-= " + _TRIM$(nm) + " =-", REDU
    IF LEN(lp) > 0 THEN CombatArtBox lp, SW - 19, 18, 4, 12, RoomShortName$(sec), CYANU
END SUB

' Back-compat shim: old call sites that only had a monster name.
SUB DrawMonsterArt (nm AS STRING)
    DrawCombatArt nm, 0
END SUB
