' ============================================================================
'  SPRITES.bas -- optional PIXEL-ART layer.
'
'  Loads transparent PNG sprites from assets/pixel-art/ (generated by ~/pixelmon)
'  on demand, caches them, and blits them scaled-to-fit into a box. Everything is
'  gated by opt_artstyle (0 = ANSI only), and every path is graceful when the file
'  isn't there yet -- so the game runs identically whether or not the art exists.
'  The pixel art COMPLEMENTS the ANSI board; it never replaces it.
' ============================================================================

' Cached image handle for a pixel-art file, loaded once. 0 = missing / failed
' (the miss is cached too, so a missing file isn't re-probed every frame).
FUNCTION Sprite& (path AS STRING)
    DIM i AS INTEGER, h AS LONG
    FOR i = 1 TO SPR_N
        IF SPR_PATH(i) = path THEN Sprite& = SPR_H(i): EXIT FUNCTION
    NEXT
    IF SPR_N >= UBOUND(SPR_H) THEN Sprite& = 0: EXIT FUNCTION
    h = 0
    IF _FILEEXISTS(path) THEN
        h = _LOADIMAGE(path, 32)                  ' 32-bit keeps the alpha channel
        IF h = -1 THEN h = 0                       ' -1 = load failed
    END IF
    SPR_N = SPR_N + 1: SPR_PATH(SPR_N) = path: SPR_H(SPR_N) = h
    Sprite& = h
END FUNCTION

' Blit a sprite scaled to fit inside a px box, centred, aspect preserved.
' Returns TRUE if something was drawn (i.e. the sprite exists).
FUNCTION DrawSpriteFit% (path AS STRING, bx AS INTEGER, by AS INTEGER, bw AS INTEGER, bh AS INTEGER)
    DIM h AS LONG, iw AS INTEGER, ih AS INTEGER, sc AS SINGLE, dw AS INTEGER, dh AS INTEGER, dx AS INTEGER, dy AS INTEGER
    DrawSpriteFit% = 0
    h = Sprite&(path)
    IF h = 0 THEN EXIT FUNCTION
    iw = _WIDTH(h): ih = _HEIGHT(h)
    IF iw < 1 OR ih < 1 THEN EXIT FUNCTION
    sc = bw / iw
    IF bh / ih < sc THEN sc = bh / ih
    dw = INT(iw * sc): dh = INT(ih * sc)
    IF dw < 1 THEN dw = 1
    IF dh < 1 THEN dh = 1
    dx = bx + (bw - dw) \ 2: dy = by + (bh - dh) \ 2
    _PUTIMAGE (dx, dy)-(dx + dw, dy + dh), h, CANVAS
    DrawSpriteFit% = -1
END FUNCTION

' Normalise a name to a sprite base: lower-case, spaces/slashes -> hyphens, drop a
' trailing plural 's'. "GIANT RATS" -> "giant-rat", "BLACK PUDDING" -> "black-pudding".
FUNCTION SpriteBase$ (nm AS STRING)
    DIM s AS STRING, o AS STRING, i AS INTEGER, c AS STRING
    s = LCASE$(_TRIM$(nm))
    o = ""
    FOR i = 1 TO LEN(s)
        c = MID$(s, i, 1)
        IF c = " " OR c = "/" OR c = "'" THEN c = "-"
        o = o + c
    NEXT
    IF RIGHT$(o, 1) = "s" AND LEN(o) > 3 THEN o = LEFT$(o, LEN(o) - 1)
    SpriteBase$ = o
END FUNCTION

' Path to a monster's sprite (searches the six category folders). "" if none.
FUNCTION MonsterSprite$ (nm AS STRING)
    DIM sbase AS STRING, i AS INTEGER, p AS STRING
    DIM cats(1 TO 6) AS STRING
    cats(1) = "humanoids": cats(2) = "animals": cats(3) = "insects"
    cats(4) = "misc": cats(5) = "beasts": cats(6) = "undead"
    sbase = SpriteBase$(nm)
    MonsterSprite$ = ""
    FOR i = 1 TO 6
        p = "assets/pixel-art/monsters/" + cats(i) + "/" + sbase + ".png"
        IF _FILEEXISTS(p) THEN MonsterSprite$ = p: EXIT FUNCTION
    NEXT
END FUNCTION

' Path to a class portrait (1 Hero / 2 Elf / 3 Superhero / 4 Wizard). "" if none.
FUNCTION ClassSprite$ (pc AS INTEGER)
    DIM nm AS STRING
    SELECT CASE pc
        CASE 1: nm = "hero"
        CASE 2: nm = "elf"
        CASE 3: nm = "superhero"
        CASE 4: nm = "wizard"
        CASE ELSE: nm = ""
    END SELECT
    IF nm = "" THEN ClassSprite$ = "" ELSE ClassSprite$ = "assets/pixel-art/classes/" + nm + ".png"
END FUNCTION

' Draw the monster's portrait in a framed box above the combat panel -- pixel-art
' modes only, and only if the sprite exists (otherwise nothing happens, and the
' fight looks exactly as it always did).
SUB DrawMonsterArt (nm AS STRING)
    DIM p AS STRING, bx AS INTEGER, by AS INTEGER, bw AS INTEGER, bh AS INTEGER
    IF opt_artstyle = 0 THEN EXIT SUB
    p = MonsterSprite$(nm)
    IF LEN(p) = 0 THEN EXIT SUB
    bw = 176: bh = 176
    bx = (SW * CW - bw) \ 2
    by = 26 * CH                                   ' floats above the combat panel (row 39)
    _DEST CANVAS
    LINE (bx - 4, by - 4)-(bx + bw + 4, by + bh + 4), BOXBG, BF
    LINE (bx - 4, by - 4)-(bx + bw + 4, by + bh + 4), REDU, B
    IF DrawSpriteFit%(p, bx, by, bw, bh) THEN
        COLOR REDU, BOXBG: PrintCentered (by \ CH) - 1, "-= " + _TRIM$(nm) + " =-"
    END IF
END SUB
