'$INCLUDE:'../include/QB64_GJ_LIB/_GJ_LIB.BI'
'$INCLUDE:'../include/Toolbox64/FileOps.bi'
'$INCLUDE:'../include/Toolbox64/ANSIPrint.bi'

DIM AS LONG CANVAS, TEMP_SCREEN, MAIN_SCREEN, BOARD_SCREEN, INTRO_SCREEN
DIM AS STRING MAIN_ANSI, BOARD_ANSI, INTRO_ANSI

DIM AS LONG MUSIC_INTRO, MUSIC_MAIN, MUSIC_FIGHT, MUSIC_TREASURE
DIM AS LONG SFX_DICE, SFX_MOVE, SFX_DOOR, SFX_SWORD, SFX_SPELL, SFX_HURT, SFX_DIE, SFX_TREASURE

INTRO_ANSI$ = LoadFile$("../assets/ansi/vermin-radioactive-logo.ans")
BOARD_ANSI$ = LoadFile$("../assets/ansi/board-132x50-no-secrets.ans")
DIM SHARED AS INTEGER SW, SH, CW, CH
SW = 132  ' SCREEN WIDTH IN CHARACTERS
SH = 51   ' SCREEN HEIGHT IN CHARACTERS
CW = 8    ' WIDTH OF 1 CHARACTER
CH = 16   ' HEIGHT OF 1 CHARACTER

$RESIZE:ON
$RESIZE:STRETCH
CANVAS& = _NEWIMAGE(SW * CW, SH * CH, 32)
_FONT CH
SCREEN CANVAS&
_FULLSCREEN _SQUAREPIXELS, _SMOOTH

MUSIC_INTRO& = _SNDOPEN("../assets/music/vr-theme.rad")
IF MUSIC_INTRO& <= 0 THEN BEEP ELSE _SNDPLAY MUSIC_INTRO&

INTRO_SCREEN& = _NEWIMAGE(SW * CW, SH * CH, 32)
' SetANSIEmulationSpeed(1)
_DEST(INTRO_SCREEN&)
ANSI_Print(INTRO_ANSI$)
SCREEN INTRO_SCREEN&
SLEEP 
_SNDSTOP MUSIC_INTRO&
_SNDCLOSE MUSIC_INTRO&

BOARD_SCREEN& = _NEWIMAGE(SW * CW, SH * CH, 32)
_DEST(BOARD_SCREEN&)
ANSI_Print(BOARD_ANSI$)
SCREEN BOARD_SCREEN&
MUSIC_MAIN& = _SNDOPEN("../assets/music/everdark.rad")
IF MUSIC_MAIN& <= 0 THEN BEEP ELSE _SNDLOOP MUSIC_MAIN&

DO:
    _LIMIT 30
LOOP UNTIL _KEYHIT = 27

_SNDSTOP MUSIC_MAIN&
_SNDCLOSE MUSIC_MAIN&

_FULLSCREEN _OFF
SCREEN 0 : _DEST 0
_DELAY 1
_FREEIMAGE CANVAS&
_FREEIMAGE INTRO_SCREEN&
_FREEIMAGE BOARD_SCREEN&
SYSTEM

'$INCLUDE:'../include/QB64_GJ_LIB/_GJ_LIB.BM'
'$INCLUDE:'../include/Toolbox64/FileOps.bas'
'$INCLUDE:'../include/Toolbox64/ANSIPrint.bas'